# Generated by Django 3.1.3 on 2020-11-10 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=18)),
                ('regdate', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('views', models.IntegerField(default=0)),
                ('contents', models.TextField()),
            ],
        ),
    ]
