# Generated by Django 3.1.3 on 2020-11-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='thumbup',
            field=models.IntegerField(default=0),
        ),
    ]
